### ISSUE TITLE
How can I run inference on BoolQ dataset?

### ISSUE THREAD

**Issue by mjeensung** [SparkJiao/Self-Training-MRC#1]
Thank you for the impressive work.

I wanted to run inference on BoolQ dataset but I couldn't find how to do it on "Readme".
Could you please provide any procedure for running your model on BoolQ dataset?

**Comment by mjeensung** [comment]
Could you provide the trained checkpoint or the preprocessed dataset on BoolQ as well?

**Comment by SparkJiao** [comment]
Hi, I'm sorry but the experimental scripts for BoolQ are still being prepared. We will upload it as soon as possible.

**Comment by SparkJiao** [comment]
@mjeensung Hi, the script path for the experiment on BoolQ has been updated on README. However we haven't checked the results. You can test by yourself. For the processing steps, please turn to the boolq reader.
Feel free for any further questions.
